# Generated by Django 5.1.1 on 2024-09-12 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_rename_course_preview_lesson_lesson_preview_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(help_text='Укажите дату оплаты', verbose_name='Дата оплаты')),
                ('paid_amount', models.PositiveIntegerField(help_text='Укажите сумму оплаты', verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(choices=[('CASH', 'наличные'), ('BANK', 'перевод на счет')], default='BANK', help_text='Выбрать способ оплаты', max_length=50, verbose_name='Способ оплаты')),
                ('paid_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course')),
                ('paid_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.lesson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
