# Generated by Django 5.1.1 on 2024-09-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=150, verbose_name='Название урока')),
                ('lesson_description', models.TextField(blank=True, max_length=1255, null=True, verbose_name='Информация об уроке')),
                ('course_preview', models.ImageField(blank=True, null=True, upload_to='lessons/images', verbose_name='Изображение для урока')),
                ('lesson_video', models.URLField(max_length=2000, verbose_name='Видео для урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='Название курса')),
                ('course_preview', models.ImageField(blank=True, null=True, upload_to='courses/images', verbose_name='Изображение для курса')),
                ('course_description', models.TextField(blank=True, max_length=1255, null=True, verbose_name='Информация о курсе')),
                ('lessons', models.ManyToManyField(help_text='Выберите урок', related_name='courses', to='materials.lesson', verbose_name='Уроки')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
