# Generated by Django 5.1.1 on 2024-09-12 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course_preview',
            new_name='lesson_preview',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Укажите курс', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='materials.course', verbose_name='Курс'),
        ),
    ]
