# Generated by Django 5.1.1 on 2024-09-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_rename_course_preview_lesson_lesson_preview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.ForeignKey(default=1, help_text='Выберите курс', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='materials.lesson', verbose_name='Урок'),
            preserve_default=False,
        ),
    ]
