# Generated by Django 5.1.1 on 2024-10-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_course_is_course_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_course_updated',
        ),
    ]
